image: elsa/gcc:9
stages:
  - compile


build-linux-gcc:
  stage: compile
  script:
    - mkdir -p build
    - cd build
    - cmake ..
    - make
    - ls
  tags:
    - linux
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build/

build-linux-clang:
  stage: compile
  script:
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_CXX_COMPILER=/usr/bin/clang++
    - make
    - ls
  tags:
    - linux
  cache:
    key: "$CI_JOB_NAME"
    paths:
      - build/
      